/*
 * Generated by @fastly/compute-js-static-publish.
 */

import type {
  ModuleAssetMap,
  PublisherServerConfigNormalized,
  ContentAssets,
  ModuleAssets,
  PublisherServer,
} from '@fastly/compute-js-static-publish';

export declare const moduleAssetMap: ModuleAssetMap;

export declare const serverConfig: PublisherServerConfigNormalized;
export declare const contentAssets: ContentAssets;
export declare const moduleAssets: ModuleAssets;

export declare function getServer(): PublisherServer;
