/*
 * Generated by @fastly/compute-js-static-publish.
 */

import type { AssetsMap, StaticAssets } from "@fastly/compute-js-static-publish";
export declare const assets: AssetsMap;
export declare const spaFile: string | false;
export declare const notFoundPageFile: string | false;
export declare const autoIndex: string[] | false;
export declare const autoExt: string[] | false;
export declare const staticAssets: StaticAssets;
