/*
 * Generated by @fastly/compute-js-static-publish.
 */

import type {
  ContentAssetMetadataMap,
} from "@fastly/compute-js-static-publish";

export declare const objectStoreName: string | null;
export declare const contentAssetMetadataMap: ContentAssetMetadataMap;
