/*
 * Copyright Fastly, Inc.
 * Licensed under the MIT license. See LICENSE file for details.
 */

export type StaticPublishRcBase = {
  // Publish ID. This is a unique string "prefix" that identifies your assets in
  // storage. This is generated by init-app and is usually not to be changed.
  publishId: string;

  // Default collection name.
  defaultCollectionName: string,

  // A directory that holds the working files built by compute-js-static-publish,
  // relative to the Compute application.
  // These files should not be committed to source control.
  staticPublisherWorkingDir: string,
};

// New KV Store config
export type StaticPublishPartialKvStoreNew = {
  storageMode: 'kv-store',
  kvStore: {
    kvStoreName: string,
  },
};

// Legacy KV Store config
export type StaticPublishPartialKvStoreLegacy = {
  storageMode?: undefined;
  kvStoreName: string,
};

// Union
export type StaticPublishPartialKvStore =
  | StaticPublishPartialKvStoreNew
  | StaticPublishPartialKvStoreLegacy
;

// KV Store config
export type StaticPublishKvStore =
  StaticPublishPartialKvStore & StaticPublishRcBase;

export function isKvStoreConfigRc(rc: unknown): rc is StaticPublishKvStore {
  if (typeof rc !== 'object' || rc == null) {
    return false;
  }

  // Legacy
  if (!('storageMode' in rc) || rc.storageMode === undefined) {
    if ('kvStoreName' in rc && typeof rc.kvStoreName === 'string') {
      return true;
    }
  }

  if ('storageMode' in rc && rc.storageMode === 'kv-store') {
    if ('kvStore' in rc && typeof rc.kvStore === 'object' && rc.kvStore != null) {
      if ('kvStoreName' in rc.kvStore && typeof rc.kvStore.kvStoreName === 'string') {
        return true;
      }
    }
  }

  return false;
}

export type StaticPublishPartialStorage =
  | StaticPublishPartialKvStore
;

export type StaticPublishRc =
  | StaticPublishKvStore
;
