/*
 * Copyright Fastly, Inc.
 * Licensed under the MIT license. See LICENSE file for details.
 */

export type StaticPublishRc = {
  // Name of KV Store to use.
  kvStoreName: string,

  // Publish ID. This is a unique string "prefix" that identifies your assets in the
  // KV Store. This is generated by init-app and is usually not to be changed.
  publishId: string;

  // Default collection name.
  defaultCollectionName: string,

  // A directory that holds the working files built by compute-js-static-publish,
  // relative to the Compute application.
  // These files should not be committed to source control.
  staticPublisherWorkingDir: string,
};
